# --- Base de données ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/opcg_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Schéma de base de données ---
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

# --- Logs SQL ---
spring.jpa.show-sql=${SHOW_SQL:true}

# --- Open-in-view ---
spring.jpa.open-in-view=false

# --- JWT ---
jwt.secret=${JWT_SECRET:UneCleTresLongueEtAleatoireDifferenteDeLAncienne}